Repository grafana/plugin-ci-workflows, pull requests merged in 2025-08, with the labels that each got.

#190 docs: Add README to each base example and add script to generate root README
  examples/base/README.md
  examples/base/README.tmpl
  examples/base/genreadme.go
  examples/base/provisioned-plugin-auto-cd/README.md
  examples/base/provisioned-plugin-manual-deployment/README.md
  examples/base/simple/README.md
Labels: documentation, type/docs

#196 fix(publish): Fix secrets not being passed to Playwright when publishing
  .github/workflows/ci.yml
Labels: bug

#198 fix(publish): Fix cd-style push events not being considered trusted
  .github/workflows/ci.yml
Labels: bug

#209 chore: Add renovate config
  .github/renovate.json5
Labels: dependencies

#199 feat(publish): Sanity check ZIP files before publishing to catalog
  .github/workflows/cd.yml
  actions/plugins/publish/check-artifacts/action.yml
  actions/plugins/publish/check-artifacts/check-artifacts.sh
Labels: enhancement

#218 ci: Switch runners for internal workflows to self-hosted ones
  .github/actionlint.yml
  .github/workflows/check-examples-readmes.yml
  .github/workflows/lint.yml
  .github/workflows/pr-checks.yml
  .github/workflows/release-please.yml
Labels: enhancement, github_actions

#225 fix: Fix "Test docs" and "Publish docs" steps failing
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: bug

#231 fix(ci): Fix NPM auth when running Playwright E2E tests
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
Labels: bug

#248 fix: revert using versioned tags
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/zizmor.yml
  actions/plugins/backend/action.yml
  actions/plugins/changelog/action.yml
  actions/plugins/changelog/parse-changelog.sh
  actions/plugins/docs/publish/action.yml
  actions/plugins/docs/publish/script.sh
  actions/plugins/docs/test/action.yml
  actions/plugins/docs/test/script.sh
  actions/plugins/frontend/action.yml
  actions/plugins/frontend/pm.sh
  actions/plugins/package/action.yml
  actions/plugins/package/package.sh
  actions/plugins/publish/check-and-create-stub/action.yml
  actions/plugins/publish/check-and-create-stub/check-and-create-stub.sh
  actions/plugins/publish/check-artifacts/action.yml
  actions/plugins/publish/check-artifacts/check-artifacts.sh
  actions/plugins/setup/action.yml
  actions/plugins/trufflehog/action.yml
  examples/base/provisioned-plugin-auto-cd/publish.yaml
  examples/base/provisioned-plugin-auto-cd/push.yaml
  examples/base/provisioned-plugin-manual-deployment/publish.yaml
  examples/base/provisioned-plugin-manual-deployment/push.yaml
  examples/base/simple/publish.yaml
  examples/base/simple/push.yaml
  release-please-config.json
Labels: github_actions

#256 fix(change-plugin-scope): use the right input name
  actions/plugins/publish/change-plugin-scope/action.yml
Labels: bug

#258 feat: add possibility to run backend tests with race detector
  actions/plugins/backend/action.yml
Labels: enhancement

#253 feat: add step to cache playwright
  .github/workflows/playwright.yml
Labels: enhancement
